apiVersion: v1
kind: Namespace
metadata:
  name: argocd-app-v1-ns
---
apiVersion: v1
kind: Pod
metadata:
  name: argocd-app-v1-pod
  namespace: argocd-app-v1-ns
  labels:
    app: argocd-app-v1-pod
    env: dev
spec:
  containers:
  - name: argocd-app-v1-container
    image: yeasy/simple-web:latest
    ports:
    - name: http
      containerPort: 80
      protocol: TCP
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-app-v1-service
  namespace: argocd-app-v1-ns
  labels:
    app: argocd-app-v1-pod
    env: dev
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  selector:
    app: argocd-app-v1-pod
    env: dev
  type: ClusterIP
